### PR TITLE
Update iControlLBO.psm1

### PR DESCRIPTION
**Pull request by aaranmcguire**
Adds the `Get-LBVirtualServer` mentioned in #3

### CODE REVIEW

**Comment by AshleyPoole** [comment]
Looks good. Only question, is it virtual server or virtual service?

**Comment by aaranmcguire** [comment]
Services ... I'll update the code later

**Comment by AshleyPoole** [comment]
Cool. Don't forget the readme file with example :-) 

Should also mention this won't work unless permissions are adjusted. Be nice to include the chmod command to run in order to adjust permissions too if not connecting as root.

**Comment by mynamewastaken** [comment]
@aaranmcguire Anything new on this?

**Pull request closed without merging**
